Add lollipop support

diff --git a/push-apk b/push-apk
--- a/push-apk
+++ b/push-apk
@@ -3,6 +3,8 @@
 
 REMOVE_ODEX_IF_EXISTS=false
 FACTORY_RESET=false
+FIND_EXISTS=false
+FIND=$(adb shell ls /system/ | tr -d '\015'|grep '^find$')
 REBOOT="reboot"
 
 show_help()
@@ -12,6 +14,16 @@ show_help()
     echo "              -d : if the odex should be removed from the system for the application (if exists)"
     echo "              -w : if data should be wiped in recovery when rebooting"
     echo ""
+}
+
+wipedata()
+{
+    echo "--wipe_data" > command
+    adb push command /data/local/tmp
+    adb shell su -c 'dd if=/data/local/tmp/command of=/cache/recovery/command'
+    adb shell su -c 'chmod 644 /cache/recovery/command'
+    adb reboot recovery
+    rm -rf command
 }
 
 if [ $# -eq 0 ]; then
@@ -29,44 +41,71 @@ done
 
 shift $((OPTIND-1))
 APK=$1
+NAME=${APK%%.*}
 
-FULL_PATH=$(find system -name $APK)
 
-if [ -z $FULL_PATH ]; then
-    echo "Unable to locate full path to $APK."
-    echo "Would you like to provide its location for installation on the device?"
-    echo "ex. system/app/myApp.apk"
-    read path
-    FULL_PATH=$path
-else
-    echo "Found full path at $FULL_PATH"
+if [ ! -z $FIND ]; then
+    FIND_EXISTS=true
 fi
 
-# Path without APK name
-FULL_PATH=${FULL_PATH%/*}
+if [ $FIND_EXISTS == true ]; then
+    FULL_PATH=$(find system -name $APK)
+else
+	FULL_PATH=$(adb shell ls /system/app | grep -w $NAME | tr -d '\r')
+	if [ -z $FULL_PATH ]; then
+	    FULL_PATH=$(adb shell ls /system/priv-app | grep -w $NAME | tr -d '\r')
+	    if [ -z $FULL_PATH ]; then
+	        echo "Unable to determine app's location"
+	        echo "Exiting...."
+	        exit 1
+	    else
+	        FULL_PATH=/system/priv-app/$NAME
+	    fi
+	else
+	    FULL_PATH=/system/app/$NAME
+	fi
+fi
+
+echo "Found apk's location at $FULL_PATH"
+
+echo "Checking app's architecture..."
+echo ""
+if [ $FIND_EXISTS == true ]; then    
+	ARCH=$(find $FULL_PATH -name arm)
+else
+	ARCH=$(adb shell ls $FULL_PATH | grep -w arm | tr -d '\r')
+	if [ -z $ARCH ]; then
+	    ARCH=$(adb shell ls $FULL_PATH | grep -w arm64 | tr -d '\r')
+    fi
+fi
+
+echo "App's architecture is $ARCH"
 
 echo ""
 echo "---- Pushing apk to device ----"
 adb push $APK /data/local/tmp
+
 echo "---- Mounting system r/w ----"
-adb shell su -c "mount -o remount,rw /system"
+adb shell su -c 'mount -o remount,rw /system'
+
 echo "---- Moving app to $FULL_PATH/$APK ----"
 adb shell su -c "dd if=/data/local/tmp/$APK of=$FULL_PATH/$APK"
 if [ $REMOVE_ODEX_IF_EXISTS == true ]; then
-    NAME=${APK%%.*}
-    ODEX_EXISTS=$(adb shell ls $FULL_PATH | tr -d '\015'|grep "^$NAME.odex")
-    if [ ! -z $ODEX_EXISTS ]; then
-        echo "Removing odex"
+    echo "---- Removing odex ----"
+    if [ ! -z $ARCH ]; then
+        adb shell su -c "rm -rf $FULL_PATH/$ARCH"
+    else
         adb shell su -c 'rm -rf $FULL_PATH/$NAME.odex'
     fi
 fi
+
 echo "---- Setting permissions ----"
 adb shell su -c "chmod 644 $FULL_PATH/$APK"
 
 if [ $FACTORY_RESET == true ]; then
-    adb shell su -c "echo '--wipe_data' > /cache/recovery/command"
+    wipedata
     REBOOT="reboot recovery"
 fi
 
 echo "---- Rebooting - ($REBOOT) ----"
-adb $REBOOT
+#adb $REBOOT
